"""Init model

Revision ID: d6b7e9f8118b
Revises: 
Create Date: 2024-12-10 18:16:25.503128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6b7e9f8118b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('km_driven', sa.Float(), nullable=True),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('max_power', sa.Float(), nullable=True),
    sa.Column('torque', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_value', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
